Name = "unit tests"

[Markers]
EndInitSection = ["START_PRINT"]
EndPrintSection = ["END_PRINT"]

[SearchStrategy]
EndInitSectionStrategy = "after_first_appear"
EndPrintSectionStrategy = "after_last_appear"

[Parameters]
# No specific parameters for unit tests

[Template]
Code = """; Generated code - Iteration {{.Iteration}}
; Generated code - End iteration {{.Iteration}}"""