# file: printers/multiline-test.toml
Name = "multiline test"

[Markers]
EndInitSection = ["START_PRINT_LINE1", "START_PRINT_LINE2"]
EndPrintSection = ["END_PRINT"]

[SearchStrategy]
EndInitSectionStrategy = "after_first_appear"
EndPrintSectionStrategy = "after_last_appear"

[Parameters]
# No specific parameters for multiline tests

[Template]
Code = """; Generated code - Iteration {{.Iteration}}
; Generated code - End iteration {{.Iteration}}"""