Name = "gcode test"

[Markers]
EndInitSection = ["M1007 S1", "G1 X0 Y0", "G1 Z0.2"]
EndPrintSection = ["G625"]

[SearchStrategy]
EndInitSectionStrategy = "after_first_appear"
EndPrintSectionStrategy = "after_last_appear"

[Parameters]
# No specific parameters for gcode tests

[Template]
Code = """; Generated code - Iteration {{.Iteration}}
; Generated code - End iteration {{.Iteration}}"""